const csvData = `Game,2-Feb-2026,31-Jan-2026
¡TACO FIGHT!,,
7 Wonders (Second Edition),,
7 Wonders Duel,,
A Fake Artist Goes to New York,,
A Message From the Stars,,
Afternova,,
Age of War,,
Agent Avenue,,
Amun-Re: The Card Game,,
Anomia,,
AQUA: Biodiversity in the Oceans,,
Arboretum,,
Arcaven's Duel,,
Archduke,,
Attack on Titan: The Last Stand,,
Aurum,,
Avatar: The Last Airbender – Fire Nation Rising,,
Azul,,
Barbarossa,,
Barcelona,,
Bärenpark,,
Bears vs Babies,,
Beasty Bar,,
Belratti,,
Betrayal at House on the Hill: 3rd Edition,,
Biss 20,,
Bitoku,,
Blazon,,
Block Block Burrito,,
Board Game Cafe Frenzy,,
Bohnanza,,
Bottle Imp,,
Brass: Birmingham,,X
Breaking Demon's Contract,,X
Bunker,,
Burgle Bros.,,
Canvas,X,
Captain Flip,,
Captain Sonar,,
Cards Against Humanity,,
Castle Combo,,
CATAN,,
Challengers!,,
Champions!,,
Cheating Moth,,
Cheese Thief,,
Cities,,
Clank!: A Deck-Building Adventure,,
Clever 4Ever,,
Cockroach Poker,,
Cockroach Salad,,
Codenames: Deep Undercover,,
Coffee Rush,,
Command of Nature,,
Concept,,
Cosmolancer,,
Coup,,
Coup: Reformation,,
Cover Your Assets,,
Cryptid Cafe,,
CuBirds,,
Cubitos,,
Cuzco,,
DCeased: Gotham City Outbreak,,
Deadly Concoctions,,
Deadwood 1876,,
Deception: Murder in Hong Kong,,
Decrypto,X,
Deduckto,,
Deep Sea Adventure,,
Disney Animated,,
Disney Villainous: The Worst Takes it All,,
Disney: The Haunted Mansion – Call of the Spirits Game,,
Dive,X,
Dixit,,
Do De Li Do,,
Dog Park,,
Dokojong,,
Donner Dinner Party,X,X
Dracula's Feast: New Blood,,
Dragon Castle,,
Dragonrealm,,
Drama Pukul 7,,
DroPolter,,
Dumb Ways to Die,,
Dungeon Mayhem,,
Dungeon Mayhem: Battle for Baldur's Gate,,
Dungeon of Mandom VIII,,
Durian,,
Dying Message,,
Earth,,
Element: Silver,,
Everdell,,
Exploding Kittens: NSFW Edition,,
Exploding Kittens: Party Pack,,
Fafnir,,
Fairy Perfume,,
Fantasy Realms,,
Faraway,,
Feed the Kraken,,
Fishing,,
Fit to Print,,
Flip 7,,
Flower Fields,,
Fog of Love,,
For the King (and Me),,
Forever Home,,
Four Gardens,,
Freaky Rumors,,
French Quarter,,
Ghosts Love Candy Too,,
GoodCritters,,
Grand Austria Hotel,,
Hail Hydra,,
Hako Onna,,
Hanabi,,
Hanamikoji,,
Hand-to-Hand Wombat,,
Happy Salmon,,
Harmonies,,
Harvest,X,
Herd Mentality,,
Heroes of Tenefyr,,
High Society,,
Hollywood 1947,,
Horrified: Dungeons & Dragons,,
HR: The Toxic Workplace Game,,
In a Grove,,
Invincible: Escape from Mars,,
IT Startup,,
IT Startup: Office Lockdown,,
Jaipur,,
Joan of Arc: Orléans Draw & Write,,
Just One,,
Kakerlakensuppe,,
Kaki Lima,,
Ketupat Rendang,,
Kick-Ass: The Board Game,,
Kingdomino,,
Kobayakawa,,
Kuih Muih,,
Let's Hit Each Other with Fake Swords,,
Living Forest,,
Lost Cities,,
Love Letter,,
Machi Koro 2,,
Magic Number Eleven,,
Magic: The Gathering – Heroes of Dominaria Board Game,,
Magical Athlete,,X
Maglev Metro,,
Make the Difference,,
MANTIS,,
Maskmen,,
MeowMeow Mia,,
Mille Fiori,,X
MLEM: Space Agency,X,
Monikers,,
Monkey Palace,,
Monopoly Deal Card Game,,
Moody Bear Kingdom,,
Moon Adventure,,
Moving Wild,,
Mr. Jack Pocket,,
Munchkin Rick and Morty,,
Muse,,
Mystery of the Temples,,
Nasi Lemak: The Game,,
Nasi Lemak: The Rendang Expansion,,
Next Station: Paris,,
Night of the Ninja,,
Nilsum,,X
Nine Tiles Extreme,,
Nine Tiles Panic,,
No Thanks!,,
Noctiluca,,
Nyet!,,
Obscurio,,
One Night Ultimate Alien,,
One Night Ultimate Werewolf,,
Only Murders in the Building: The Game,,
Onstage,,
OrganATTACK!,,
Overseers,,
Pasaraya: Supermarket Manager,,
Patchwork,,
Petal Plotters,,
Petrichor,,
Photosynthesis,,
Piles! A Fast-Paced Free-For-All,,
Pixies,,
Poetry for Neanderthals,,
Poetry for Neanderthals: NSFW Edition,,
Point City,,
Point Salad,,
Ponzi Scheme,,
Pot de Vin,,
Power Hungry Pets,,
Prêt-à-Porter,,
Primordial Secrets,,
Quickity Pickity,,
Rafter Five,,
Rallyman: DIRT,,
Ramen! Ramen!,,
Ready Set Bet,,
Really Loud Librarians,,
Red Rising,,
Redwood,,
Reef,,
Regicide,,
Risk Strike,,
Rummikub,,
Runemasters,,
Rush M.D.,,
Saboteur,,
Saint Petersburg,,
Scholars of the South Tigris,X,
Scream: The Game,,
Sea Salt & Paper,,
Sea Salt & Paper: Extra Salt,,
Secret Hitler,,
Shake That City,,
Shake Up,,
Shardhunters,,
Sheriff of Nottingham: 2nd Edition,,
Shop Until You Drop,,
Silver Fang,,
Skull,,
Skull King,,
Sky Team,,
Skyrockets: Festivals of Fire,,
Slingz: The Darker Side,,
Snake Oil,,
So Clover!,,
Solenia,,
Sonic Roll,,
Souvenirs from Venice,,
Spell Wars,,
Spire's End,,
Spire's End: Hildegard,,
Splendor,,
Spyfall: Time Travel,,
Starry Night Sky,,
Startups,,
Stereo Mind,,
Stranger Things: Upside Down,,
Summer Camp,,
Survivor: The Tribe Has Spoken,,
Sushi Go Party!,,
Taco Cat Goat Cheese Pizza,,
Take 5,,
Take Time,,
Tanto Cuore: Romantic Vacation,,
Tapestry,,
Telestrations,,
Terra Nova,,
That Escalated Quickly,,
That's Not a Hat: Pop Culture,,
The Bloody Inn,,
The Castles of Burgundy,,
The Chameleon,,
The Cikgu Life,,
The Crew: The Quest for Planet Nine,,
The Fox in the Forest,,
The Gang,,
The Gig,,
The Gig: Encore! Expansion,,
The Grizzled,,
The Lord of the Rings: Duel for Middle-earth,,
The Lord of the Rings: The Fellowship of the Ring – Trick-Taking Game,,
The Malaysian Dream,,
The Mind,,
The Resistance: Avalon,,
The Valley of Alchemists,,
Things in Rings,,
Throw Throw Burrito,,
Ticket to Ride: Europe,,
Toil & Troublez,,
Tokaido,,
Tortuga 1667,,
Town 77,,
Traitors Aboard,,
Trekking the National Parks: Second Edition,,
Trishaw Frenzy,,
TROLL,,
Tsukiji,,
Two Rooms and a Boom,,
Ultimate Werewolf: Deluxe Edition,,
Unstable Unicorns: NSFW Base Game,,
Verdant,X,
Viticulture Essential Edition,,
Wakanda Forever,,
Walking in Provence,,
War of the Three Kingdoms: Kingdom Wars,,
Wavelength,,
Werewords Deluxe Edition,,
Whale Riders,,
Whale to Look,,
When I Dream,,
White Castle,X,
Wine Cellar,,
Without Fail,,
Wizard,,
World of Warcraft: Wrath of the Lich King,,
Wriggle Roulette,,
WWE Superstar Showdown,,
Zoo Vadis,,X`